// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eyhqkhdksvqijxdtbugv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5aHFraGRrc3ZxaWp4ZHRidWd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NjI3ODYsImV4cCI6MjA2NTEzODc4Nn0.CmrBE6myXFG24e6uJEc6sVioJQW92BurtT0oQLLK_dg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);